import pandas as pd
import numpy as np
import os
import shutil
import json
import random
import time
import config
import scipy.stats
import warnings

# Suppress annoying joblib/loky cleanup warnings
warnings.filterwarnings("ignore", category=UserWarning, module="joblib.externals.loky.backend.resource_tracker")

from feature_engine import FeatureEngine
from genome import GenomeFactory, Strategy
from backtest import BacktestEngine
from backtest.statistics import deflated_sharpe_ratio, estimated_sharpe_ratio
import uuid

class EvolutionaryAlphaFactory:
    def __init__(self, data, survivors_file, population_size=None, generations=100, decay_rate=0.99, target_col='log_ret', prediction_mode=False):
        self.training_id = uuid.uuid4().hex[:8]
        print(f"🆔 Training Run ID: {self.training_id}")
        
        self.data = data
        self.pop_size = population_size if population_size else config.EVO_BATCH_SIZE
        self.generations = generations
        self.decay_rate = decay_rate
        self.survivors_file = survivors_file
        self.prediction_mode = prediction_mode
        
        self.backtester = BacktestEngine(
            data, 
            cost_bps=config.COST_BPS, 
            target_col=target_col,
            annualization_factor=config.ANNUALIZATION_FACTOR,
            account_size=config.ACCOUNT_SIZE
        )
        
        self.factory = GenomeFactory(survivors_file)
        train_data = data.iloc[:self.backtester.train_idx]
        self.factory.set_stats(train_data)
        
        self.population = []
        # HOF now stores dicts: {'strat': Strategy, 'fit': float, 'sig': np.array, 'gen': int}
        # This list ensures DIVERSITY. We do not allow correlated strategies (>0.7) to coexist here.
        self.hall_of_fame = [] 
        
        # Track total unique strategies evaluated for DSR calculation
        self.total_strategies_evaluated = 0

    def cleanup(self):
        if hasattr(self, 'backtester'):
            self.backtester.shutdown()

    def initialize_population(self, horizon=None):
        print(f"  🎲 Initializing Population with {self.pop_size} Random Strategies.")
        # SMALL DATA MODE: Max genes to prevent overfitting (controlled by config)
        self.population = [self.factory.create_strategy((config.GENE_COUNT_MIN, config.GENE_COUNT_MAX)) for _ in range(self.pop_size)]

    def crossover(self, p1, p2):
        child = Strategy(name=f"Child_{random.randint(1000,9999)}")
        
        n_long = random.randint(config.GENE_COUNT_MIN, config.GENE_COUNT_MAX)
        n_short = random.randint(config.GENE_COUNT_MIN, config.GENE_COUNT_MAX)
        
        combined_long = p1.long_genes + p2.long_genes
        combined_short = p1.short_genes + p2.short_genes
        combined_regime = p1.regime_genes + p2.regime_genes
        
        child.long_genes = [g.copy() for g in random.sample(combined_long, min(len(combined_long), n_long))]
        child.short_genes = [g.copy() for g in random.sample(combined_short, min(len(combined_short), n_short))]
        
        if combined_regime:
            n_regime = random.randint(0, min(len(combined_regime), 2))
            child.regime_genes = [g.copy() for g in random.sample(combined_regime, n_regime)]
        
        child.recalculate_concordance()
        return child

    def update_hall_of_fame(self, candidates, gen, horizon=None):
        """
        Intelligently updates the Hall of Fame with new candidates.
        Enforces diversity: A new candidate is only added if it is UNCORRELATED with existing HOF entries,
        OR if it is correlated but strictly BETTER (higher fitness).
        """
        if not candidates: return
        
        # 1. Generate Signals for Candidates (Validation Slice)
        # We use the full available development set (Train+Val) for correlation to be robust
        # Using just Val might be too short/noisy.
        limit_idx = self.backtester.val_idx
        
        # We need to temporarily ensure context for these candidates
        # self.backtester.ensure_context(candidates) # generated by generate_signal_matrix
        
        cand_signals_full = self.backtester.generate_signal_matrix(candidates)
        cand_signals = cand_signals_full[:limit_idx]
        
        # Expectancy Filter (Churn Prevention)
        rets_batch, trades_batch = self.backtester.run_simulation_batch(
            cand_signals, 
            candidates, 
            self.backtester.open_vec[:limit_idx], 
            self.backtester.times_vec[:limit_idx],
            time_limit=horizon,
            highs=self.backtester.high_vec[:limit_idx],
            lows=self.backtester.low_vec[:limit_idx],
            atr=self.backtester.atr_vec[:limit_idx]
        )

        for i, cand in enumerate(candidates):
            if cand.fitness < 0.1: continue # Ignore junk
            
            n_trades = trades_batch[i]
            total_ret = np.sum(rets_batch[:, i])

            # Adaptive Expectancy Filter (Ramp up requirements)
            # Phase 1 (0-10%): Just positive (Survival)
            # Phase 2 (10-30%): 1 bps (Growth)
            # Phase 3 (30%+): 2 bps (Maturity)
            phase_1 = max(1, int(self.generations * 0.10))
            phase_2 = max(2, int(self.generations * 0.30))
            
            if gen < phase_1:
                thresh = 0.0
            elif gen < phase_2:
                thresh = 0.00005 # 0.5 bps
            else:
                thresh = 0.0001  # 1.0 bps

            if n_trades > 0:
                avg_ret = total_ret / n_trades
                if avg_ret < thresh:
                    continue
            else:
                continue # No trades = No alpha
            
            cand_sig = cand_signals[:, i]
            cand_fit = cand.fitness
            
            # Check against existing HOF
            is_unique = True
            
            # We iterate through the HOF. 
            # If we find a correlated strategy, we compare fitness.
            for hof_entry in self.hall_of_fame:
                existing_sig = hof_entry['sig']
                
                # Fast Correlation Check
                if np.std(cand_sig) == 0 or np.std(existing_sig) == 0:
                    corr = 0.0
                else:
                    corr = np.corrcoef(cand_sig, existing_sig)[0, 1]
                
                if corr > 0.70: # Correlation Threshold (0.7 = Strong Similarity)
                    is_unique = False
                    
                    # Found a cluster match. Is the new one better?
                    if cand_fit > hof_entry['fit']:
                        old_fit = hof_entry['fit']
                        # Replace the existing champion of this cluster
                        hof_entry['strat'] = cand
                        hof_entry['fit'] = cand_fit
                        hof_entry['sig'] = cand_sig
                        hof_entry['gen'] = gen
                        print(f"    ♻️  HOF Cluster Replacement: {cand.name} (Corr: {corr:.2f} | Fit: {old_fit:.2f} -> {cand_fit:.2f})")
                    break # Stop checking, we handled this cluster
            
            if is_unique:
                # Add new distinct alpha source
                self.hall_of_fame.append({
                    'strat': cand,
                    'fit': cand_fit,
                    'sig': cand_sig,
                    'gen': gen
                })
                print(f"    ⭐ HOF New Alpha: {cand.name} (Fit: {cand_fit:.2f})")

        # Sort HOF by Fitness
        self.hall_of_fame.sort(key=lambda x: x['fit'], reverse=True)
        
        # Cap Size (Keep top 500 DISTINCT strategies)
        if len(self.hall_of_fame) > 500:
            self.hall_of_fame = self.hall_of_fame[:500]

    def evolve(self, horizon=60):
        # random.seed(42)  <-- Removed to ensure diversity across runs
        # np.random.seed(42) <-- Removed to ensure diversity across runs
        
        self.initialize_population(horizon=horizon)
        
        generations_without_improvement = 0
        global_best_fitness = -999.0
        
        for gen in range(self.generations):
            start_time = time.time()
            
            # Dynamic Trade Filter (Horizon-Aware Scaling)
            target_final = max(10, int(config.MIN_TRADES_COEFFICIENT / horizon + 5))
            scaling_factor = target_final / 10.0
            
            current_min_trades = int(3 * scaling_factor)
            if gen >= 5: current_min_trades = int(6 * scaling_factor)
            if gen >= 15: current_min_trades = target_final
            
            # Increment trial counter for DSR
            self.total_strategies_evaluated += len(self.population)

            # 1. Evaluate using Rolling Walk-Forward Validation
            wfv_results = self.backtester.evaluate_walk_forward(self.population, folds=4, time_limit=horizon, min_trades=current_min_trades)
            wfv_scores = wfv_results['sortino'].values
            
            # 2. Penalties (Dominance & Complexity)
            feature_counts = {}
            for strat in self.population:
                used_features = set()
                for gene in strat.long_genes + strat.short_genes:
                    if hasattr(gene, 'feature'): used_features.add(gene.feature)
                    elif hasattr(gene, 'feature_left'): 
                        used_features.add(gene.feature_left)
                        used_features.add(gene.feature_right)
                for f in used_features:
                    feature_counts[f] = feature_counts.get(f, 0) + 1
            
            for i, strat in enumerate(self.population):
                n_genes = len(strat.long_genes) + len(strat.short_genes)
                complexity_penalty = n_genes * config.COMPLEXITY_PENALTY_PER_GENE
                
                dom_penalty = 0.0
                strat_features = set()
                for gene in strat.long_genes + strat.short_genes:
                    if hasattr(gene, 'feature'): strat_features.add(gene.feature)
                    elif hasattr(gene, 'feature_left'): 
                        strat_features.add(gene.feature_left)
                        strat_features.add(gene.feature_right)
                
                for f in strat_features:
                    count = feature_counts.get(f, 0)
                    ratio = count / self.pop_size
                    if ratio > config.DOMINANCE_PENALTY_THRESHOLD:
                         dom_penalty += (ratio - config.DOMINANCE_PENALTY_THRESHOLD) * config.DOMINANCE_PENALTY_MULTIPLIER
                
                # Quadratic Complexity Penalty: Punish bloat progressively harder
                # 4 genes -> 16 * C (Small)
                # 8 genes -> 64 * C (Huge)
                # We scale by 0.5 to keep the base impact reasonable for small strategies
                complexity_penalty = 0.5 * (n_genes ** 2) * config.COMPLEXITY_PENALTY_PER_GENE
                
                wfv_scores[i] -= (complexity_penalty + dom_penalty)
                strat.fitness = wfv_scores[i]

            # 3. Stats & Early Stopping
            best_idx = np.argmax(wfv_scores)
            best_fitness = wfv_scores[best_idx]
            
            if gen % 5 == 0:
                print(f"Gen {gen} | Best WFV Score: {best_fitness:.4f}")
            
            if best_fitness > global_best_fitness:
                global_best_fitness = best_fitness
                generations_without_improvement = 0
            else:
                generations_without_improvement += 1
                
            if generations_without_improvement >= 15:
                print(f"🛑 Early Stopping Triggered.")
                break
            
            # 4. Update Diverse Hall of Fame
            sorted_indices = np.argsort(wfv_scores)[::-1]
            top_50_indices = sorted_indices[:50]
            top_50_strats = [self.population[i] for i in top_50_indices]
            
            # Tag generation
            for s in top_50_strats:
                if not hasattr(s, 'generation_found'): s.generation_found = gen
            
            self.update_hall_of_fame(top_50_strats, gen, horizon=horizon)

            # 5. Selection for Next Gen
            num_elite = int(self.pop_size * config.ELITE_PERCENTAGE)
            elites = [self.population[i] for i in sorted_indices[:num_elite]]
            
            new_population = elites[:50] # Keep top 50 strictly
            
            # Elite Mutation
            n_mutants = int(self.pop_size * 0.20)
            mutant_source = elites[:max(1, int(len(elites)*0.2))]
            for _ in range(n_mutants):
                if not mutant_source: break
                parent = random.choice(mutant_source)
                child = Strategy(name=f"Mutant_{random.randint(1000,9999)}")
                child.long_genes = [g.copy() for g in parent.long_genes]
                child.short_genes = [g.copy() for g in parent.short_genes]
                child.regime_genes = [g.copy() for g in parent.regime_genes]
                
                genes_to_mutate = child.long_genes + child.short_genes + child.regime_genes
                if genes_to_mutate:
                    target_genes = random.sample(genes_to_mutate, min(len(genes_to_mutate), 2))
                    for g in target_genes: g.mutate(self.factory.features)
                child.cleanup()
                child.recalculate_concordance()
                new_population.append(child)
            
            # Immigration
            n_immigrants = int(self.pop_size * config.IMMIGRATION_PERCENTAGE)
            for _ in range(n_immigrants):
                new_population.append(self.factory.create_strategy((config.GENE_COUNT_MIN, config.GENE_COUNT_MAX)))
            
            # Crossover
            while len(new_population) < self.pop_size:
                p1, p2 = random.sample(elites, 2)
                child = self.crossover(p1, p2)
                mut_rate = config.MUTATION_RATE
                for g in child.long_genes + child.short_genes:
                    if random.random() < mut_rate: g.mutate(self.factory.features)
                child.cleanup()
                child.recalculate_concordance()
                new_population.append(child)
                
            self.population = new_population
            print(f"  Gen {gen} completed in {time.time()-start_time:.2f}s | HOF Size: {len(self.hall_of_fame)}")

        # --- FINAL SELECTION ---
        # The Hall of Fame is already filtered for diversity and sorted by fitness.
        print(f"\n--- 🛡️ FINAL SELECTION (Using Diverse HOF) ---")
        
        top_candidates = [entry['strat'] for entry in self.hall_of_fame[:100]]
        val_fitness_map = {entry['strat'].name: entry['fit'] for entry in self.hall_of_fame[:100]}
        
        if top_candidates:
            # Evaluate on Test Set
            test_res = self.backtester.evaluate_population(top_candidates, set_type='test', return_series=False, prediction_mode=False, time_limit=horizon, min_trades=10)
            
            # We need Test Returns for OOS PSR and Val Returns for Selection DSR
            # Let's generate signals for both ranges
            val_start, val_end = self.backtester.train_idx, self.backtester.val_idx
            test_start, test_end = self.backtester.val_idx, len(self.backtester.open_vec)
            
            full_signals = self.backtester.generate_signal_matrix(top_candidates)
            val_signals = full_signals[val_start:val_end]
            test_signals = full_signals[test_start:test_end]

            # Batch Sim Validation
            val_rets_batch, _ = self.backtester.run_simulation_batch(
                val_signals,
                top_candidates,
                self.backtester.open_vec[val_start:val_end],
                self.backtester.times_vec.iloc[val_start:val_end] if hasattr(self.backtester.times_vec, 'iloc') else self.backtester.times_vec[val_start:val_end],
                time_limit=horizon,
                highs=self.backtester.high_vec[val_start:val_end],
                lows=self.backtester.low_vec[val_start:val_end],
                atr=self.backtester.atr_vec[val_start:val_end]
            )
            
            # Batch Sim Test
            test_rets_batch, _ = self.backtester.run_simulation_batch(
                test_signals,
                top_candidates,
                self.backtester.open_vec[test_start:test_end],
                self.backtester.times_vec.iloc[test_start:test_end] if hasattr(self.backtester.times_vec, 'iloc') else self.backtester.times_vec[test_start:test_end],
                time_limit=horizon,
                highs=self.backtester.high_vec[test_start:test_end],
                lows=self.backtester.low_vec[test_start:test_end],
                atr=self.backtester.atr_vec[test_start:test_end]
            )

            output = []
            for i, s in enumerate(top_candidates):
                if i >= len(test_res): break
                
                # 1. Validation DSR (Did we mine this result?)
                val_r = val_rets_batch[:, i]
                val_sr = estimated_sharpe_ratio(val_r, config.ANNUALIZATION_FACTOR)
                val_skew = scipy.stats.skew(val_r)
                val_kurt = scipy.stats.kurtosis(val_r)
                
                dsr_val = deflated_sharpe_ratio(
                    observed_sr=val_sr,
                    returns=val_r,
                    n_trials=self.total_strategies_evaluated, # The penalty
                    var_returns=np.var(val_r),
                    skew_returns=val_skew,
                    kurt_returns=val_kurt,
                    annualization_factor=config.ANNUALIZATION_FACTOR
                )
                
                # 2. Test PSR (Is the OOS result real?)
                # n_trials = 1 because we didn't optimize on this data
                test_r = test_rets_batch[:, i]
                test_sr = estimated_sharpe_ratio(test_r, config.ANNUALIZATION_FACTOR)
                test_skew = scipy.stats.skew(test_r)
                test_kurt = scipy.stats.kurtosis(test_r)
                
                psr_test = deflated_sharpe_ratio(
                    observed_sr=test_sr,
                    returns=test_r,
                    n_trials=1, 
                    var_returns=np.var(test_r),
                    skew_returns=test_skew,
                    kurt_returns=test_kurt,
                    annualization_factor=config.ANNUALIZATION_FACTOR
                )
                
                # --- STRICT SURVIVAL FILTER ---
                # Kill Switch: If it fails OOS, it dies here.
                if psr_test < 0.9 or float(test_res.iloc[i]['sortino']) < 0.5 or float(test_res.iloc[i]['total_return']) <= 0:
                    continue
                # -------------------------------
                
                strat_data = s.to_dict()
                strat_data['test_sortino'] = float(test_res.iloc[i]['sortino'])
                strat_data['test_return'] = float(test_res.iloc[i]['total_return'])
                strat_data['test_trades'] = int(test_res.iloc[i]['trades'])
                strat_data['robust_score'] = float(val_fitness_map.get(s.name, -999.0)) 
                strat_data['dsr_val'] = float(dsr_val)
                strat_data['psr_test'] = float(psr_test)
                strat_data['training_id'] = self.training_id
                strat_data['generation'] = getattr(s, 'generation_found', -1)
                output.append(strat_data)
            
            # Save Apex Strategies
            os.makedirs(config.DIRS['STRATEGIES_DIR'], exist_ok=True)
            out_path = os.path.join(config.DIRS['STRATEGIES_DIR'], f"apex_strategies_{horizon}.json")
            
            # --- PORTFOLIO ---
            print("\n--- 🧩 CONSTRUCTING PORTFOLIO (From Uncorrelated HOF) ---")
            # Since HOF is already <0.7 correlated, we just pick the top 5 that are <0.5 correlated for extra safety
            
            cand_signals = self.backtester.generate_signal_matrix(top_candidates)
            # val_start, val_end = self.backtester.train_idx, self.backtester.val_idx
            cand_signals_val = cand_signals[val_start:val_end]
            
            # Rank candidates by Composite Score (Robust Val + Test Sortino)
            scored_candidates = []
            for i, strat in enumerate(top_candidates):
                if i >= len(test_res): continue
                
                val_score = val_fitness_map.get(strat.name, 0.0)
                t_sortino = float(test_res.iloc[i]['sortino'])
                t_ret = float(test_res.iloc[i]['total_return'])
                
                # Retrieve DSR from output list
                d_val = next((x['dsr_val'] for x in output if x['name'] == strat.name), 0.0)
                p_test = next((x['psr_test'] for x in output if x['name'] == strat.name), 0.0)

                # Filter out losers based on Validation Score (Robustness)
                if val_score <= 0: continue

                # Composite Score: Robust Val ONLY (Blind to Test)
                composite_score = val_score 
                
                scored_candidates.append({
                    'strat': strat,
                    'orig_idx': i,
                    'score': composite_score,
                    'dsr_val': d_val,
                    'psr_test': p_test
                })
            
            # Sort by Composite Score Descending
            scored_candidates.sort(key=lambda x: x['score'], reverse=True)

            portfolio = []
            portfolio_indices = []
            
            for item in scored_candidates:
                # if len(portfolio) >= 5: break # REMOVED LIMIT per user request
                
                strat = item['strat']
                orig_idx = item['orig_idx']
                
                # --- STRICT PORTFOLIO FILTER ---
                # 1. Val DSR Check: Did we actually find a signal?
                # Lowered to 0.1 to 'squeeze blood' from small data
                if item['dsr_val'] < 0.1: 
                    continue
                
                # 2. Test Survival Check: Did it survive the recent regime?
                # We need positive OOS returns.
                # Find the return from the output list
                t_ret = next((x['test_return'] for x in output if x['name'] == strat.name), -1.0)
                if t_ret <= 0:
                    continue
                # -------------------------------

                if not portfolio:
                    portfolio.append(strat)
                    portfolio_indices.append(orig_idx)
                    continue
                
                current_sig = cand_signals_val[:, orig_idx]
                is_uncorrelated = True
                for p_idx in portfolio_indices:
                    existing_sig = cand_signals_val[:, p_idx]
                    corr = np.corrcoef(current_sig, existing_sig)[0, 1] if np.std(current_sig) > 0 and np.std(existing_sig) > 0 else 0
                    if corr > 0.5: # Stricter threshold for portfolio
                        is_uncorrelated = False
                        break
                
                if is_uncorrelated:
                    portfolio.append(strat)
                    portfolio_indices.append(orig_idx)
            
            print(f"Selected {len(portfolio)} Strategies for Ensemble.")
            
            # Print Portfolio Strategy Stats
            print("\n  Ensemble Constituent Performance:")
            print(f"  {'Rank':<4} | {'Name':<15} | {'Robust (Val)':<12} | {'Val DSR':<8} | {'Test PSR':<8} | {'Sortino (Test)':<14} | {'Ret (Test)':<10} | {'Trades':<6}")
            print("  " + "-" * 105)
            
            for p_rank, (strat, orig_idx) in enumerate(zip(portfolio, portfolio_indices)):
                # Get Test Metrics using the original index in top_candidates/test_res
                if orig_idx < len(test_res):
                    t_sortino = float(test_res.iloc[orig_idx]['sortino'])
                    t_ret = float(test_res.iloc[orig_idx]['total_return'])
                    t_trades = int(test_res.iloc[orig_idx]['trades'])
                    
                    val_score = val_fitness_map.get(strat.name, -999.0)
                    dsr_v = next((x['dsr_val'] for x in output if x['name'] == strat.name), 0.0)
                    psr_t = next((x['psr_test'] for x in output if x['name'] == strat.name), 0.0)
                    
                    print(f"  {p_rank+1:<4} | {strat.name:<15} | {val_score:<12.4f} | {dsr_v:.4f}   | {psr_t:.4f}   | {t_sortino:<14.4f} | {t_ret*100:<9.2f}% | {t_trades:<6}")
            
            
            # Save Portfolio
            port_data = [s.to_dict() for s in portfolio]
            with open(os.path.join(config.DIRS['STRATEGIES_DIR'], f"apex_portfolio_{horizon}.json"), "w") as f:
                json.dump(port_data, f, indent=4)

            # Persist Strategies (Merge with existing)
            existing_data = []
            if os.path.exists(out_path):
                try:
                    with open(out_path, "r") as f: existing_data = json.load(f)
                except: pass
            
            combined = existing_data + output
            # Dedup by name
            seen = set()
            unique = []
            combined.sort(key=lambda x: x.get('robust_score', -999), reverse=True)
            for s in combined:
                if s['name'] not in seen:
                    unique.append(s)
                    seen.add(s['name'])
            
            with open(out_path, "w") as f: json.dump(unique[:1000], f, indent=4)
            print(f"\n💾 Saved results to {out_path}")
        else:
            print("No strategies survived.")

import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--survivors", type=str, required=True)
    parser.add_argument("--horizon", type=int, default=60)
    parser.add_argument("--pop_size", type=int, default=5000)
    parser.add_argument("--gens", type=int, default=50)
    args = parser.parse_args()

    if not os.path.exists(config.DIRS['FEATURE_MATRIX']):
        print("❌ Feature Matrix not found.")
        exit(1)
        
    bars_df = pd.read_parquet(config.DIRS['FEATURE_MATRIX'])
    
    factory = EvolutionaryAlphaFactory(
        bars_df, 
        args.survivors, 
        population_size=args.pop_size, 
        generations=args.gens,
        target_col='log_ret',
        prediction_mode=False
    )
    
    try:
        factory.evolve(horizon=args.horizon)
    finally:
        factory.cleanup()
    
    # Old cleanup block removed as it is now handled by factory.cleanup()
