from .zscore import ZScoreGene
from .soft_zscore import SoftZScoreGene
from .relational import RelationalGene
from .squeeze import SqueezeGene
from .correlation import CorrelationGene
from .flux import FluxGene
from .efficiency import EfficiencyGene
from .divergence import DivergenceGene
from .event import EventGene
from .cross import CrossGene
from .persistence import PersistenceGene
from .extrema import ExtremaGene
from .consecutive import ConsecutiveGene
from .delta import DeltaGene
from .time import TimeGene
from .seasonality import SeasonalityGene
from .utils import gene_from_dict
