from .relational import RelationalGene
from .delta import DeltaGene
from .flux import FluxGene
from .divergence import DivergenceGene
from .efficiency import EfficiencyGene
from .zscore import ZScoreGene
from .correlation import CorrelationGene
from .time import TimeGene
from .consecutive import ConsecutiveGene
from .cross import CrossGene
from .persistence import PersistenceGene
from .squeeze import SqueezeGene
from .event import EventGene
from .extrema import ExtremaGene
from .utils import gene_from_dict
